#!/usr/bin/env bash

set -euo pipefail

# Install uv in a temporary directory
tempdir=$(mktemp -d)
curl -LsSf https://astral.sh/uv/0.9.8/install.sh | env UV_UNMANAGED_INSTALL=$tempdir sh -s -- -q > /dev/null
PATH=$tempdir:$PATH

set -x
uv sync --frozen